import re

with open('server/routers/chat.py', 'r') as f:
    text = f.read()

# 1. Import time
if 'import time' not in text:
    text = "import time\n" + text

# 2. Add start time at entry
tgt1 = '''async def chat_endpoint(request: ChatRequest, http_request: Request, db: Session = Depends(get_db)):'''
repl1 = '''async def chat_endpoint(request: ChatRequest, http_request: Request, db: Session = Depends(get_db)):
    t0_start = time.time()'''
text = text.replace(tgt1, repl1)

# 3. Before dialogue processor
tgt2 = '''    try:
        dialogue_result = await dialogue_processor.process_message('''
repl2 = '''    try:
        t1_dialog_start = time.time()
        print(f"⏱️ [1. Auth & Session Init] Cost: {t1_dialog_start - t0_start:.3f}s")
        dialogue_result = await dialogue_processor.process_message('''
text = text.replace(tgt2, repl2)

# 4. RAG search
tgt3 = '''        if rag_enabled:
            if last_user_message:
                # 根据用户部门层级获取允许访问的知识库分类'''
repl3 = '''        if rag_enabled:
            if last_user_message:
                t2_rag_start = time.time()
                print(f"⏱️ [2. Dialogue & Pre-flight] Cost: {t2_rag_start - t1_dialog_start:.3f}s")
                # 根据用户部门层级获取允许访问的知识库分类'''
text = text.replace(tgt3, repl3)

# 5. RAG end
tgt4 = '''                print(f"🔍 Fetching RAG context for: {last_user_message} (allowed: {allowed_categories})")
                rag_context = await fetch_rag_context(last_user_message, allowed_categories=allowed_categories)
        
        # 硬拦截'''
repl4 = '''                print(f"🔍 Fetching RAG context for: {last_user_message} (allowed: {allowed_categories})")
                rag_context = await fetch_rag_context(last_user_message, allowed_categories=allowed_categories)
                t3_rag_end = time.time()
                print(f"⏱️ [3. RAG Retrieval] Cost: {t3_rag_end - t2_rag_start:.3f}s")
        
        # 硬拦截'''
text = text.replace(tgt4, repl4)

# 6. LLM generator start
tgt5 = '''        async def generate():
            full_response = ""'''
repl5 = '''        t4_llm_start = time.time()
        print(f"⏱️ [4. Prompt Prep & Context] Cost: {t4_llm_start - locals().get('t3_rag_end', t4_llm_start):.3f}s")
        
        async def generate():
            full_response = ""'''
text = text.replace(tgt5, repl5)

# 7. LLM First token
tgt6 = '''                if full_response == "":
                    print(f"🤖 First Token generated by Provider!")
                
                full_response += item'''
repl6 = '''                if full_response == "":
                    t5_first_token = time.time()
                    print(f"⏱️ [5. First Token Delay (TTFT)] Cost: {t5_first_token - t4_llm_start:.3f}s")
                    print(f"⏱️ [TOTAL. User Ask -> First Token] Cost: {t5_first_token - t0_start:.3f}s")
                
                full_response += item'''
text = text.replace(tgt6, repl6)


# Write back
with open('server/routers/chat.py', 'w') as f:
    f.write(text)

